######################################################################
# Automatically generated by qmake (2.01a) jue dic 4 17:57:33 2014
######################################################################

QT       += core gui

greaterThan(QT_MAJOR_VERSION, 4): QT += widgets

TEMPLATE = app
TARGET = ParalelismQT
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += mainwindow.h
FORMS += mainwindow.ui
SOURCES += main.cpp mainwindow.cpp

OTHER_FILES += \
    ParalelismQT22.pro
